### ISSUE TITLE
404 error on my activity

### ISSUE THREAD

**Issue by vishnureddy7** [DivySrivastava/spruce#4]
When pressed on my activity 404 not found error is occurring and also the full stack trace of error should not be displayed on the website, it should be surpassed. PFA

![Screenshot_20190414-083615](https://user-images.githubusercontent.com/17957871/56087832-9df6a780-5e90-11e9-98b1-46ca0904afec.png)

**Comment by DivySrivastava** [comment]
The activity feature is still a pending feature and I agree with you about the full stack error..
It is just for testing now...

**Comment by DivySrivastava** [comment]
It should be working now!
Thanks!
